/**
 * DATA LAYER
 * Static configuration and MCU entry lists
 */

const PARENTS = {
  "iron-man": {
    poster: "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    title: "Iron Man",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "126 min",
    imdb: "https://www.imdb.com/title/tt0371746/",
  },
  "incredible-hulk": {
    poster: "/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    title: "The Incredible Hulk",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "112 min",
    imdb: "https://www.imdb.com/title/tt0800080/",
  },
  "iron-man-2": {
    poster: "/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
    title: "Iron Man 2",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "124 min",
    imdb: "https://www.imdb.com/title/tt1228705/",
  },
  thor: {
    poster: "/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
    title: "Thor",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "115 min",
    imdb: "https://www.imdb.com/title/tt0800369/",
  },
  "cap-1": {
    poster: "/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
    title: "Captain America: The First Avenger",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "124 min",
    imdb: "https://www.imdb.com/title/tt0458339/",
  },
  avengers: {
    poster: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    title: "The Avengers",
    type: "movie",
    phase: 1,
    saga: "infinity",
    runtime: "143 min",
    imdb: "https://www.imdb.com/title/tt0848228/",
  },
  "iron-man-3": {
    poster: "/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
    title: "Iron Man 3",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "130 min",
    imdb: "https://www.imdb.com/title/tt1300854/",
  },
  "thor-dark-world": {
    poster: "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
    title: "Thor: The Dark World",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "112 min",
    imdb: "https://www.imdb.com/title/tt1981115/",
  },
  "cap-winter-soldier": {
    poster: "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    title: "Captain America: The Winter Soldier",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "136 min",
    imdb: "https://www.imdb.com/title/tt1843866/",
  },
  "guardians-1": {
    poster: "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    title: "Guardians of the Galaxy",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "121 min",
    imdb: "https://www.imdb.com/title/tt2015381/",
  },
  "age-of-ultron": {
    poster: "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    title: "Avengers: Age of Ultron",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "141 min",
    imdb: "https://www.imdb.com/title/tt2395427/",
  },
  "ant-man": {
    poster: "/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
    title: "Ant-Man",
    type: "movie",
    phase: 2,
    saga: "infinity",
    runtime: "117 min",
    imdb: "https://www.imdb.com/title/tt0478970/",
  },
  "cap-civil-war": {
    poster: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    title: "Captain America: Civil War",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "147 min",
    imdb: "https://www.imdb.com/title/tt3498820/",
  },
  "doctor-strange": {
    poster: "/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
    title: "Doctor Strange",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "115 min",
    imdb: "https://www.imdb.com/title/tt1211837/",
  },
  "guardians-2": {
    poster: "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
    title: "Guardians of the Galaxy Vol. 2",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "136 min",
    imdb: "https://www.imdb.com/title/tt3896198/",
  },
  "spider-man-homecoming": {
    poster: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    title: "Spider-Man: Homecoming",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "133 min",
    imdb: "https://www.imdb.com/title/tt2250912/",
  },
  "thor-ragnarok": {
    poster: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    title: "Thor: Ragnarok",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "130 min",
    imdb: "https://www.imdb.com/title/tt3501632/",
  },
  "black-panther": {
    poster: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    title: "Black Panther",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "134 min",
    imdb: "https://www.imdb.com/title/tt1825683/",
  },
  "infinity-war": {
    poster: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    title: "Avengers: Infinity War",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "149 min",
    imdb: "https://www.imdb.com/title/tt4154756/",
  },
  "ant-man-wasp": {
    poster: "/2mnK5VtjzYRWvQB1zLhZWtAJwzk.jpg",
    title: "Ant-Man and the Wasp",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "118 min",
    imdb: "https://www.imdb.com/title/tt5095030/",
  },
  "captain-marvel": {
    poster: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
    title: "Captain Marvel",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "123 min",
    imdb: "https://www.imdb.com/title/tt4154664/",
  },
  endgame: {
    poster: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    title: "Avengers: Endgame",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "181 min",
    imdb: "https://www.imdb.com/title/tt4154796/",
  },
  "spider-man-ffh": {
    poster: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    title: "Spider-Man: Far From Home",
    type: "movie",
    phase: 3,
    saga: "infinity",
    runtime: "129 min",
    imdb: "https://www.imdb.com/title/tt6320628/",
  },
  "black-widow": {
    poster: "/7JPpIjhD2V0sKyFvhB9khUMa30d.jpg",
    title: "Black Widow",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "134 min",
    imdb: "https://www.imdb.com/title/tt3480822/",
  },
  "shang-chi": {
    poster: "/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg",
    title: "Shang-Chi and the Legend of the Ten Rings",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "132 min",
    imdb: "https://www.imdb.com/title/tt9376612/",
  },
  eternals: {
    poster: "/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
    title: "Eternals",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "156 min",
    imdb: "https://www.imdb.com/title/tt9032400/",
  },
  "spider-man-nwh": {
    poster: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "148 min",
    imdb: "https://www.imdb.com/title/tt10872600/",
  },
  "doctor-strange-2": {
    poster: "/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
    title: "Doctor Strange in the Multiverse of Madness",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "126 min",
    imdb: "https://www.imdb.com/title/tt9419884/",
  },
  "thor-love-thunder": {
    poster: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    title: "Thor: Love and Thunder",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "118 min",
    imdb: "https://www.imdb.com/title/tt10648342/",
  },
  "bp-wakanda-forever": {
    poster: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    title: "Black Panther: Wakanda Forever",
    type: "movie",
    phase: 4,
    saga: "multiverse",
    runtime: "161 min",
    imdb: "https://www.imdb.com/title/tt9114286/",
  },
  "ant-man-quantumania": {
    poster: "/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    title: "Ant-Man and The Wasp: Quantumania",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "124 min",
    imdb: "https://www.imdb.com/title/tt10954600/",
  },
  "guardians-3": {
    poster: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    title: "Guardians of the Galaxy Vol. 3",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "150 min",
    imdb: "https://www.imdb.com/title/tt6791350/",
  },
  marvels: {
    poster: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    title: "The Marvels",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "105 min",
    imdb: "https://www.imdb.com/title/tt10676048/",
  },
  "deadpool-wolverine": {
    poster: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    title: "Deadpool & Wolverine",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "128 min",
    imdb: "https://www.imdb.com/title/tt6263850/",
  },
  "cap-brave-new-world": {
    poster: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    title: "Captain America: Brave New World",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "TBD",
    imdb: "https://www.imdb.com/title/tt14513804/",
  },
  thunderbolts: {
    poster: "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    title: "Thunderbolts*",
    type: "movie",
    phase: 5,
    saga: "multiverse",
    runtime: "TBD",
    imdb: "https://www.imdb.com/title/tt20969586/",
  },
  "fantastic-four": {
    poster: "/abqOz6EL3yXyOOafCPZxjL1M5bQ.jpg",
    title: "The Fantastic Four: First Steps",
    type: "movie",
    phase: 6,
    saga: "multiverse",
    runtime: "TBD",
    imdb: "https://www.imdb.com/title/tt10676052/",
  },
  "the-consultant": {
    poster: "/8ldbDrhGwvdro1hj63AUzzskOGa.jpg",
    title: "The Consultant",
    type: "oneshot",
    phase: 1,
    saga: "infinity",
    runtime: "4 min",
    imdb: "https://www.imdb.com/title/tt2011118/",
  },
  "thor-hammer-oneshot": {
    poster: "/ugrdgmZlSuiavH0NFurhlUPIRD0.jpg",
    title: "A Funny Thing Happened on the Way to Thor’s Hammer",
    type: "oneshot",
    phase: 1,
    saga: "infinity",
    runtime: "4 min",
    imdb: "https://www.imdb.com/title/tt2011109/",
  },
  "item-47": {
    poster: "/hnSxG8clwLuAXEkp9emc8HCUcHD.jpg",
    title: "Item 47",
    type: "oneshot",
    phase: 1,
    saga: "infinity",
    runtime: "12 min",
    imdb: "https://www.imdb.com/title/tt2247732/",
  },
  "agent-carter-oneshot": {
    poster: "/4vFKKWPvCVDJTOWiwReBfpAMScP.jpg",
    title: "Agent Carter",
    type: "oneshot",
    phase: 2,
    saga: "infinity",
    runtime: "15 min",
    imdb: "https://www.imdb.com/title/tt3067038/",
  },
  "all-hail-king": {
    poster: "/ydYH8Rv5KbL2WtBJjj79RpR3wQp.jpg",
    title: "All Hail the King",
    type: "oneshot",
    phase: 2,
    saga: "infinity",
    runtime: "14 min",
    imdb: "https://www.imdb.com/title/tt3438640/",
  },
  "team-thor-1": {
    poster: "/jVSmX89BvsQV2z3wh2IVYVNVw1a.jpg",
    title: "Team Thor",
    type: "oneshot",
    phase: 3,
    saga: "infinity",
    runtime: "4 min",
    imdb: "https://www.imdb.com/title/tt6016776/",
  },
  "team-thor-2": {
    poster: "/2jmP71A5Un0jDNqBesDPQSN8hjJ.jpg",
    title: "Team Thor: Part 2",
    type: "oneshot",
    phase: 3,
    saga: "infinity",
    runtime: "4 min",
    imdb: "https://www.imdb.com/title/tt6599818/",
  },
  "team-darryl": {
    poster: "/edroTAeTEM9ILyAnumA0ALxRSne.jpg",
    title: "Team Darryl",
    type: "oneshot",
    phase: 3,
    saga: "infinity",
    runtime: "6 min",
    imdb: "https://www.imdb.com/title/tt8023090/",
  },
  "werewolf-night": {
    poster: "/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
    title: "Werewolf By Night",
    type: "special",
    phase: 4,
    saga: "multiverse",
    runtime: "52 min",
    imdb: "https://www.imdb.com/title/tt15318872/",
  },
  "gg-holiday-special": {
    poster: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    title: "The Guardians of the Galaxy Holiday Special",
    type: "special",
    phase: 4,
    saga: "multiverse",
    runtime: "44 min",
    imdb: "https://www.imdb.com/title/tt13623136/",
  },
  "agent-carter-s1": {
    poster: "/7kqIsjjDMZA5GRMH5VCdQYZJqc6.jpg",
    title: "Agent Carter — Season 1",
    type: "series",
    phase: "legacy",
    runtime: "8 episodes",
    imdb: "https://www.imdb.com/title/tt3475734/",
  },
  "agent-carter-s2": {
    poster: "/7kqIsjjDMZA5GRMH5VCdQYZJqc6.jpg",
    title: "Agent Carter — Season 2",
    type: "series",
    phase: "legacy",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt3475734/",
  },
  "aos-s1": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 1",
    type: "series",
    phase: "legacy",
    runtime: "22 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-s2": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 2",
    type: "series",
    phase: "legacy",
    runtime: "22 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-s3": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 3",
    type: "series",
    phase: "legacy",
    runtime: "22 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-s4": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 4",
    type: "series",
    phase: "legacy",
    runtime: "22 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-slingshot": {
    poster: "/bwJej7WdmGRMCMyuDlotwAqVX7S.jpg",
    title: "Agents of S.H.I.E.L.D.: Slingshot",
    type: "series",
    phase: "legacy",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt6313900/",
  },
  "aos-s5": {
    poster: "/cWJhivXNzgiAChitT5dWVEwJDCP.jpg",
    title: "Agents of S.H.I.E.S.D. — Season 5",
    type: "series",
    phase: "legacy",
    runtime: "22 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-s6": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 6",
    type: "series",
    phase: "legacy",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "aos-s7": {
    poster: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    title: "Agents of S.H.I.E.L.D. — Season 7",
    type: "series",
    phase: "legacy",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt2364582/",
  },
  "daredevil-s1": {
    poster: "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    title: "Daredevil — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322312/",
  },
  "daredevil-s2": {
    poster: "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    title: "Daredevil — Season 2",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322312/",
  },
  "daredevil-s3": {
    poster: "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    title: "Daredevil — Season 3",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322312/",
  },
  "jessica-jones-s1": {
    poster: "/1ghmaDw650NuUpGI7mYq6xE2QE2.jpg",
    title: "Jessica Jones — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt2357547/",
  },
  "jessica-jones-s2": {
    poster: "/1ghmaDw650NuUpGI7mYq6xE2QE2.jpg",
    title: "Jessica Jones — Season 2",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt2357547/",
  },
  "jessica-jones-s3": {
    poster: "/1ghmaDw650NuUpGI7mYq6xE2QE2.jpg",
    title: "Jessica Jones — Season 3",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt2357547/",
  },
  "luke-cage-s1": {
    poster: "/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
    title: "Luke Cage — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322314/`",
  },
  "luke-cage-s2": {
    poster: "/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
    title: "Luke Cage — Season 2",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322314/",
  },
  "iron-fist-s1": {
    poster: "/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
    title: "Iron Fist — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt3322310/",
  },
  "iron-fist-s2": {
    poster: "/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
    title: "Iron Fist — Season 2",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt3322310/",
  },
  "the-defenders": {
    poster: "/g4QCPffsJqElwCu8f1JvvuaRVsc.jpg",
    title: "The Defenders — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "8 episodes",
    imdb: "https://www.imdb.com/title/tt4230076/",
  },
  "inhumans-s1": {
    poster: "/dMHgFwX2cRPcuMSZ0rsBNap01o6.jpg",
    title: "Inhumans — Season 1",
    type: "series",
    phase: "legacy",
    runtime: "8 episodes",
    imdb: "https://www.imdb.com/title/tt4154858/",
  },
  "punisher-s1": {
    poster: "/tM6xqRKXoloH9UchaJEyyRE9O1w.jpg",
    title: "The Punisher — Season 1",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt5675620/",
  },
  "punisher-s2": {
    poster: "/tM6xqRKXoloH9UchaJEyyRE9O1w.jpg",
    title: "The Punisher — Season 2",
    type: "series",
    phase: "defenders",
    saga: "multiverse",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt5675620/",
  },
  "runaways-s1": {
    poster: "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
    title: "Runaways — Season 1",
    type: "series",
    phase: "legacy",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt1236246/",
  },
  "runaways-s2": {
    poster: "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
    title: "Runaways — Season 2",
    type: "series",
    phase: "legacy",
    runtime: "13 episodes",
    imdb: "https://www.imdb.com/title/tt1236246/",
  },
  "runaways-s3": {
    poster: "/hnHEhbzh0F7kN3Ah1lzRjtQuW16.jpg",
    title: "Runaways — Season 3",
    type: "series",
    phase: "legacy",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt1236246/",
  },
  "cloak-dagger-s1": {
    poster: "/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
    title: "Cloak & Dagger — Season 1",
    type: "series",
    phase: "legacy",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt5614844/",
  },
  "cloak-dagger-s2": {
    poster: "/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
    title: "Cloak & Dagger — Season 2",
    type: "series",
    phase: "legacy",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt5614844/",
  },
  wandavision: {
    poster: "/frobUz2X5Pc8OiVZU8Oo5K3NKMM.jpg",
    title: "WandaVision",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt9140560/",
  },
  "falcon-ws": {
    poster: "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    title: "The Falcon and the Winter Soldier",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt9208876/",
  },
  "loki-s1": {
    poster: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    title: "Loki — Season 1",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt9140554/",
  },
  "loki-s2": {
    poster: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    title: "Loki — Season 2",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt9140554/",
  },
  "what-if-s1": {
    poster: "/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    title: "What If…? — Season 1",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt10168312/",
  },
  "what-if-s2": {
    poster: "/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    title: "What If…? — Season 2",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt10168312/",
  },
  "what-if-s3": {
    poster: "/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    title: "What If…? — Season 3",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "8 episodes",
    imdb: "https://www.imdb.com/title/tt10168312/",
  },
  "marvel-zombies": {
    poster: "/mwKj9ERGFXsWot0nXgQ5yMQf9I7.jpg",
    title: "Marvel Zombies",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "4 episodes",
    imdb: "https://www.imdb.com/title/tt16027014/",
  },
  hawkeye: {
    poster: "/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
    title: "Hawkeye",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt10160804/",
  },
  "moon-knight": {
    poster: "/YksR65as1ppF2N48TJAh2PLamX.jpg",
    title: "Moon Knight",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt10234724/",
  },
  "ms-marvel": {
    poster: "/3HWWh92kZbD7odwJX7nKmXNZsYo.jpg",
    title: "Ms. Marvel",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt10857164/",
  },
  "she-hulk": {
    poster: "/5xz2orV8f0usyrfGNshcoXHmiaV.jpg",
    title: "She-Hulk: Attorney at Law",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt10857160/",
  },
  "secret-invasion": {
    poster: "/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
    title: "Secret Invasion",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt13157618/",
  },
  "i-am-groot-s1": {
    poster: "/3QfQYECgu6DX5UUWCBvv1Fl0BAJ.jpg",
    title: "I Am Groot — Season 1",
    type: "series",
    phase: 4,
    saga: "multiverse",
    runtime: "5 shorts",
    imdb: "https://www.imdb.com/title/tt13623148/",
  },
  "i-am-groot-s2": {
    poster: "/3QfQYECgu6DX5UUWCBvv1Fl0BAJ.jpg",
    title: "I Am Groot — Season 2",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "5 shorts",
    imdb: "https://www.imdb.com/title/tt13623148/",
  },
  echo: {
    poster: "/vFyJH630cF68LohVYjQW49074Sy.jpg",
    title: "Echo",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "5 episodes",
    imdb: "https://www.imdb.com/title/tt13966962/",
  },
  "agatha-all-along": {
    poster: "/mGsxKwXUjojitRv2E9qMTbxbBRd.jpg",
    title: "Agatha All Along",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt15571732/",
  },
  "daredevil-ba-s1": {
    poster: "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    title: "Daredevil: Born Again — Season 1",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt18923754/",
  },
  "daredevil-ba-s2": {
    poster: "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    title: "Daredevil: Born Again — Season 2",
    type: "series",
    phase: 6,
    saga: "multiverse",
    runtime: "9 episodes",
    imdb: "https://www.imdb.com/title/tt18923754/",
  },
  "ironheart-s1": {
    poster: "/dOh6MJpdlQhYpLBhzhNQeYGKTZ5.jpg",
    title: "Ironheart — Season 1",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "6 episodes",
    imdb: "https://www.imdb.com/title/tt13623126/",
  },
  "eyes-of-wakanda": {
    poster: "/bG23nZW96LxmWkJjsagRZI9hF6t.jpg",
    title: "Eyes of Wakanda",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "4 episodes",
    imdb: "https://www.imdb.com/title/tt13968252/",
  },
  "wonder-man-s1": {
    poster: "/6yy9nQlFt2l6UVWzrfhszFCaZ5C.jpg",
    title: "Wonder Man — Season 1",
    type: "series",
    phase: 5,
    saga: "multiverse",
    runtime: "10 episodes",
    imdb: "https://www.imdb.com/title/tt21066182/",
  },
};

const SAGA_CONFIG = {
  infinity: { title: "The Infinity Saga", color: "#8b5cf6" },
  multiverse: { title: "The Multiverse Saga", color: "#06b6d4" },
};

const PHASE_CONFIG = {
  1: { title: "Phase One", saga: "infinity" },
  2: { title: "Phase Two", saga: "infinity" },
  3: { title: "Phase Three", saga: "infinity" },
  4: { title: "Phase Four", saga: "multiverse" },
  5: { title: "Phase Five", saga: "multiverse" },
  6: { title: "Phase Six", saga: "multiverse" },
  defenders: { title: "The Defenders Saga", saga: "multiverse" },
  legacy: { title: "Marvel Television & Legacy", saga: null },
};

const THEMES = {
  cosmic: {
    label: "Cosmic Multiverse",
    color: "#8b5cf6",
    secondary: "#06b6d4",
    desc: "Nebula purple & neon cyan",
  },
  classic: {
    label: "Classic Marvel",
    color: "#dc2626",
    secondary: "#d4af37",
    desc: "Avenger red & aged gold",
  },
  stark: {
    label: "Stark Tech",
    color: "#0ea5e9",
    secondary: "#ef4444",
    desc: "HUD blue & arc reactor red",
  },
  mystic: {
    label: "Mystic Arts",
    color: "#c27839",
    secondary: "#991b1b",
    desc: "Portal amber & cloak red",
  },
};

const RELEASE_ORDER = [
  {
    id: "r01",
    parentKey: "iron-man",
    title: "Iron Man",
    releaseDate: "2008-05-01",
  },
  {
    id: "r02",
    parentKey: "incredible-hulk",
    title: "The Incredible Hulk",
    releaseDate: "2008-06-01",
  },
  {
    id: "r03",
    parentKey: "iron-man-2",
    title: "Iron Man 2",
    releaseDate: "2010-04-01",
  },
  { id: "r04", parentKey: "thor", title: "Thor", releaseDate: "2011-04-01" },
  {
    id: "r05",
    parentKey: "cap-1",
    title: "Captain America: The First Avenger",
    releaseDate: "2011-07-01",
  },
  {
    id: "r06",
    parentKey: "the-consultant",
    title: "The Consultant",
    releaseDate: "2011-09-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r07",
    parentKey: "thor-hammer-oneshot",
    title: "A Funny Thing Happened on the Way to Thor’s Hammer",
    releaseDate: "2011-10-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r08",
    parentKey: "avengers",
    title: "The Avengers",
    releaseDate: "2012-04-01",
  },
  {
    id: "r09",
    parentKey: "item-47",
    title: "Item 47",
    releaseDate: "2012-09-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r10",
    parentKey: "iron-man-3",
    title: "Iron Man 3",
    releaseDate: "2013-04-01",
  },
  {
    id: "r11",
    parentKey: "agent-carter-oneshot",
    title: "Agent Carter",
    releaseDate: "2013-09-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r12",
    parentKey: "aos-s1",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2013-09-01",
    releaseNote: "Season 1",
  },
  {
    id: "r13",
    parentKey: "thor-dark-world",
    title: "Thor: The Dark World",
    releaseDate: "2013-11-01",
  },
  {
    id: "r14",
    parentKey: "all-hail-king",
    title: "All Hail the King",
    releaseDate: "2014-02-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r15",
    parentKey: "cap-winter-soldier",
    title: "Captain America: The Winter Soldier",
    releaseDate: "2014-03-01",
  },
  {
    id: "r16",
    parentKey: "guardians-1",
    title: "Guardians of the Galaxy",
    releaseDate: "2014-07-01",
  },
  {
    id: "r17",
    parentKey: "aos-s2",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2014-09-01",
    releaseNote: "Season 2",
  },
  {
    id: "r18",
    parentKey: "agent-carter-s1",
    title: "Agent Carter",
    releaseDate: "2015-01-01",
    releaseNote: "Season 1",
  },
  {
    id: "r19",
    parentKey: "daredevil-s1",
    title: "Daredevil",
    releaseDate: "2015-04-01",
    releaseNote: "Season 1",
  },
  {
    id: "r20",
    parentKey: "age-of-ultron",
    title: "Avengers: Age of Ultron",
    releaseDate: "2015-04-01",
  },
  {
    id: "r21",
    parentKey: "ant-man",
    title: "Ant-Man",
    releaseDate: "2015-07-01",
  },
  {
    id: "r22",
    parentKey: "aos-s3",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2015-09-01",
    releaseNote: "Season 3",
  },
  {
    id: "r23",
    parentKey: "jessica-jones-s1",
    title: "Jessica Jones",
    releaseDate: "2015-11-01",
    releaseNote: "Season 1",
  },
  {
    id: "r24",
    parentKey: "agent-carter-s2",
    title: "Agent Carter",
    releaseDate: "2016-01-01",
    releaseNote: "Season 2",
  },
  {
    id: "r25",
    parentKey: "daredevil-s2",
    title: "Daredevil",
    releaseDate: "2016-03-01",
    releaseNote: "Season 2",
  },
  {
    id: "r26",
    parentKey: "cap-civil-war",
    title: "Captain America: Civil War",
    releaseDate: "2016-04-01",
  },
  {
    id: "r27",
    parentKey: "team-thor-1",
    title: "Team Thor",
    releaseDate: "2016-08-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r28",
    parentKey: "aos-s4",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2016-09-01",
    releaseNote: "Season 4",
  },
  {
    id: "r29",
    parentKey: "luke-cage-s1",
    title: "Luke Cage",
    releaseDate: "2016-09-01",
    releaseNote: "Season 1",
  },
  {
    id: "r30",
    parentKey: "doctor-strange",
    title: "Doctor Strange",
    releaseDate: "2016-10-01",
  },
  {
    id: "r31",
    parentKey: "team-thor-2",
    title: "Team Thor: Part 2",
    releaseDate: "2017-02-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r32",
    parentKey: "iron-fist-s1",
    title: "Iron Fist",
    releaseDate: "2017-03-01",
    releaseNote: "Season 1",
  },
  {
    id: "r33",
    parentKey: "guardians-2",
    title: "Guardians of the Galaxy Vol. 2",
    releaseDate: "2017-04-01",
  },
  {
    id: "r34",
    parentKey: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
    releaseDate: "2017-07-01",
  },
  {
    id: "r35",
    parentKey: "the-defenders",
    title: "The Defenders",
    releaseDate: "2017-08-01",
    releaseNote: "Season 1",
  },
  {
    id: "r36",
    parentKey: "inhumans-s1",
    title: "Inhumans",
    releaseDate: "2017-09-01",
    releaseNote: "Season 1",
  },
  {
    id: "r37",
    parentKey: "thor-ragnarok",
    title: "Thor: Ragnarok",
    releaseDate: "2017-10-01",
  },
  {
    id: "r38",
    parentKey: "punisher-s1",
    title: "The Punisher",
    releaseDate: "2017-11-01",
    releaseNote: "Season 1",
  },
  {
    id: "r39",
    parentKey: "runaways-s1",
    title: "Runaways",
    releaseDate: "2017-11-01",
    releaseNote: "Season 1",
  },
  {
    id: "r40",
    parentKey: "aos-s5",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2017-12-01",
    releaseNote: "Season 5",
  },
  {
    id: "r41",
    parentKey: "black-panther",
    title: "Black Panther",
    releaseDate: "2018-02-01",
  },
  {
    id: "r42",
    parentKey: "team-darryl",
    title: "Team Darryl",
    releaseDate: "2018-02-01",
    releaseNote: "One-Shot",
  },
  {
    id: "r43",
    parentKey: "jessica-jones-s2",
    title: "Jessica Jones",
    releaseDate: "2018-03-01",
    releaseNote: "Season 2",
  },
  {
    id: "r44",
    parentKey: "infinity-war",
    title: "Avengers: Infinity War",
    releaseDate: "2018-04-01",
  },
  {
    id: "r45",
    parentKey: "cloak-dagger-s1",
    title: "Cloak & Dagger",
    releaseDate: "2018-06-01",
    releaseNote: "Season 1",
  },
  {
    id: "r46",
    parentKey: "luke-cage-s2",
    title: "Luke Cage",
    releaseDate: "2018-06-01",
    releaseNote: "Season 2",
  },
  {
    id: "r47",
    parentKey: "ant-man-wasp",
    title: "Ant-Man and the Wasp",
    releaseDate: "2018-07-01",
  },
  {
    id: "r48",
    parentKey: "iron-fist-s2",
    title: "Iron Fist",
    releaseDate: "2018-09-01",
    releaseNote: "Season 2",
  },
  {
    id: "r49",
    parentKey: "daredevil-s3",
    title: "Daredevil",
    releaseDate: "2018-10-01",
    releaseNote: "Season 3",
  },
  {
    id: "r50",
    parentKey: "runaways-s2",
    title: "Runaways",
    releaseDate: "2018-12-01",
    releaseNote: "Season 2",
  },
  {
    id: "r51",
    parentKey: "punisher-s2",
    title: "The Punisher",
    releaseDate: "2019-01-01",
    releaseNote: "Season 2",
  },
  {
    id: "r52",
    parentKey: "captain-marvel",
    title: "Captain Marvel",
    releaseDate: "2019-03-01",
  },
  {
    id: "r53",
    parentKey: "cloak-dagger-s2",
    title: "Cloak & Dagger",
    releaseDate: "2019-04-01",
    releaseNote: "Season 2",
  },
  {
    id: "r54",
    parentKey: "endgame",
    title: "Avengers: Endgame",
    releaseDate: "2019-04-01",
  },
  {
    id: "r55",
    parentKey: "aos-s6",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2019-05-01",
    releaseNote: "Season 6",
  },
  {
    id: "r56",
    parentKey: "jessica-jones-s3",
    title: "Jessica Jones",
    releaseDate: "2019-06-01",
    releaseNote: "Season 3",
  },
  {
    id: "r57",
    parentKey: "spider-man-ffh",
    title: "Spider-Man: Far From Home",
    releaseDate: "2019-07-01",
  },
  {
    id: "r58",
    parentKey: "runaways-s3",
    title: "Runaways",
    releaseDate: "2019-12-01",
    releaseNote: "Season 3",
  },
  {
    id: "r59",
    parentKey: "aos-s7",
    title: "Agents of S.H.I.E.L.D.",
    releaseDate: "2020-05-01",
    releaseNote: "Season 7",
  },
  {
    id: "r60",
    parentKey: "wandavision",
    title: "WandaVision",
    releaseDate: "2021-01-01",
  },
  {
    id: "r61",
    parentKey: "falcon-ws",
    title: "The Falcon and the Winter Soldier",
    releaseDate: "2021-03-01",
  },
  {
    id: "r62",
    parentKey: "loki-s1",
    title: "Loki",
    releaseDate: "2021-06-01",
    releaseNote: "Season 1",
  },
  {
    id: "r63",
    parentKey: "black-widow",
    title: "Black Widow",
    releaseDate: "2021-07-01",
  },
  {
    id: "r64",
    parentKey: "what-if-s1",
    title: "What If…?",
    releaseDate: "2021-08-01",
    releaseNote: "Season 1",
  },
  {
    id: "r65",
    parentKey: "shang-chi",
    title: "Shang-Chi and the Legend of the Ten Rings",
    releaseDate: "2021-09-01",
  },
  {
    id: "r66",
    parentKey: "eternals",
    title: "Eternals",
    releaseDate: "2021-11-01",
  },
  {
    id: "r67",
    parentKey: "hawkeye",
    title: "Hawkeye",
    releaseDate: "2021-11-01",
  },
  {
    id: "r68",
    parentKey: "spider-man-nwh",
    title: "Spider-Man: No Way Home",
    releaseDate: "2021-12-01",
  },
  {
    id: "r69",
    parentKey: "moon-knight",
    title: "Moon Knight",
    releaseDate: "2022-03-01",
  },
  {
    id: "r70",
    parentKey: "doctor-strange-2",
    title: "Doctor Strange in the Multiverse of Madness",
    releaseDate: "2022-05-01",
  },
  {
    id: "r71",
    parentKey: "ms-marvel",
    title: "Ms. Marvel",
    releaseDate: "2022-06-01",
  },
  {
    id: "r72",
    parentKey: "thor-love-thunder",
    title: "Thor: Love and Thunder",
    releaseDate: "2022-07-01",
  },
  {
    id: "r73",
    parentKey: "i-am-groot-s1",
    title: "I Am Groot",
    releaseDate: "2022-08-01",
    releaseNote: "Season 1",
  },
  {
    id: "r74",
    parentKey: "she-hulk",
    title: "She-Hulk: Attorney at Law",
    releaseDate: "2022-08-01",
  },
  {
    id: "r75",
    parentKey: "werewolf-night",
    title: "Werewolf By Night",
    releaseDate: "2022-10-01",
    releaseNote: "Special",
  },
  {
    id: "r76",
    parentKey: "bp-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
    releaseDate: "2022-11-01",
  },
  {
    id: "r77",
    parentKey: "gg-holiday-special",
    title: "The Guardians of the Galaxy Holiday Special",
    releaseDate: "2022-11-01",
    releaseNote: "Special",
  },
  {
    id: "r78",
    parentKey: "ant-man-quantumania",
    title: "Ant-Man and The Wasp: Quantumania",
    releaseDate: "2023-02-01",
  },
  {
    id: "r79",
    parentKey: "guardians-3",
    title: "Guardians of the Galaxy Vol. 3",
    releaseDate: "2023-05-01",
  },
  {
    id: "r80",
    parentKey: "secret-invasion",
    title: "Secret Invasion",
    releaseDate: "2023-06-01",
  },
  {
    id: "r81",
    parentKey: "i-am-groot-s2",
    title: "I Am Groot",
    releaseDate: "2023-09-01",
    releaseNote: "Season 2",
  },
  {
    id: "r82",
    parentKey: "loki-s2",
    title: "Loki",
    releaseDate: "2023-10-01",
    releaseNote: "Season 2",
  },
  {
    id: "r83",
    parentKey: "marvels",
    title: "The Marvels",
    releaseDate: "2023-11-01",
  },
  {
    id: "r84",
    parentKey: "what-if-s2",
    title: "What If…?",
    releaseDate: "2023-12-01",
    releaseNote: "Season 2",
  },
  { id: "r85", parentKey: "echo", title: "Echo", releaseDate: "2024-01-01" },
  {
    id: "r86",
    parentKey: "deadpool-wolverine",
    title: "Deadpool & Wolverine",
    releaseDate: "2024-07-01",
  },
  {
    id: "r87",
    parentKey: "agatha-all-along",
    title: "Agatha All Along",
    releaseDate: "2024-09-01",
  },
  {
    id: "r88",
    parentKey: "what-if-s3",
    title: "What If…?",
    releaseDate: "2024-12-01",
    releaseNote: "Season 3",
  },
  {
    id: "r89",
    parentKey: "cap-brave-new-world",
    title: "Captain America: Brave New World",
    releaseDate: "2025-02-01",
  },
  {
    id: "r90",
    parentKey: "daredevil-ba-s1",
    title: "Daredevil: Born Again",
    releaseDate: "2025-03-01",
    releaseNote: "Season 1",
  },
  {
    id: "r91",
    parentKey: "thunderbolts",
    title: "Thunderbolts*",
    releaseDate: "2025-05-01",
  },
  {
    id: "r92",
    parentKey: "ironheart-s1",
    title: "Ironheart",
    releaseDate: "2025-06-01",
    releaseNote: "Season 1",
  },
  {
    id: "r93",
    parentKey: "fantastic-four",
    title: "The Fantastic Four: First Steps",
    releaseDate: "2025-07-01",
  },
  {
    id: "r94",
    parentKey: "eyes-of-wakanda",
    title: "Eyes of Wakanda",
    releaseDate: "2025-08-01",
  },
  {
    id: "r95",
    parentKey: "marvel-zombies",
    title: "Marvel Zombies",
    releaseDate: "2025-09-01",
  },
  {
    id: "r96",
    parentKey: "wonder-man-s1",
    title: "Wonder Man",
    releaseDate: "2026-01-01",
    releaseNote: "Season 1",
  },
  {
    id: "r97",
    parentKey: "daredevil-ba-s2",
    title: "Daredevil: Born Again",
    releaseDate: "2026-03-01",
    releaseNote: "Season 2",
  },
];

const CHRONO_ORDER = [
  { id: "c001", parentKey: "eyes-of-wakanda", title: "Eyes of Wakanda" },
  {
    id: "c002",
    parentKey: "cap-1",
    title: "Captain America: The First Avenger",
  },
  {
    id: "c003",
    parentKey: "agent-carter-oneshot",
    title: "Agent Carter",
    sub: "One-Shot",
  },
  {
    id: "c004",
    parentKey: "agent-carter-s1",
    title: "Agent Carter",
    sub: "Season 1",
  },
  {
    id: "c005",
    parentKey: "agent-carter-s2",
    title: "Agent Carter",
    sub: "Season 2",
  },
  {
    id: "c006",
    parentKey: "captain-marvel",
    title: "Captain Marvel",
    note: "Mid-credits scene set after Infinity War",
  },
  { id: "c007", parentKey: "iron-man", title: "Iron Man" },
  { id: "c008", parentKey: "iron-man-2", title: "Iron Man 2" },
  { id: "c009", parentKey: "incredible-hulk", title: "The Incredible Hulk" },
  {
    id: "c010",
    parentKey: "the-consultant",
    title: "The Consultant",
    sub: "One-Shot",
  },
  {
    id: "c011",
    parentKey: "thor-hammer-oneshot",
    title: "A Funny Thing Happened on the Way to Thor’s Hammer",
    sub: "One-Shot",
  },
  { id: "c012", parentKey: "thor", title: "Thor" },
  { id: "c013", parentKey: "avengers", title: "The Avengers" },
  { id: "c014", parentKey: "item-47", title: "Item 47", sub: "One-Shot" },
  {
    id: "c015",
    parentKey: "aos-s1",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 1 · Eps 1–7",
  },
  { id: "c016", parentKey: "thor-dark-world", title: "Thor: The Dark World" },
  {
    id: "c017",
    parentKey: "aos-s1",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 1 · Eps 8–16",
  },
  { id: "c018", parentKey: "iron-man-3", title: "Iron Man 3" },
  {
    id: "c019",
    parentKey: "all-hail-king",
    title: "All Hail the King",
    sub: "One-Shot",
  },
  {
    id: "c020",
    parentKey: "cap-winter-soldier",
    title: "Captain America: The Winter Soldier",
  },
  {
    id: "c021",
    parentKey: "aos-s1",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 1 · Eps 17–22",
  },
  { id: "c022", parentKey: "guardians-1", title: "Guardians of the Galaxy" },
  {
    id: "c023",
    parentKey: "guardians-2",
    title: "Guardians of the Galaxy Vol. 2",
  },
  {
    id: "c024",
    parentKey: "i-am-groot-s1",
    title: "I Am Groot",
    sub: "Season 1",
  },
  {
    id: "c025",
    parentKey: "i-am-groot-s2",
    title: "I Am Groot",
    sub: "Season 2",
  },
  {
    id: "c026",
    parentKey: "daredevil-s1",
    title: "Daredevil",
    sub: "Season 1",
  },
  {
    id: "c027",
    parentKey: "aos-s2",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 2 · Eps 1–10",
  },
  {
    id: "c028",
    parentKey: "jessica-jones-s1",
    title: "Jessica Jones",
    sub: "Season 1",
  },
  {
    id: "c029",
    parentKey: "aos-s2",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 2 · Eps 11–19",
  },
  { id: "c030", parentKey: "age-of-ultron", title: "Avengers: Age of Ultron" },
  {
    id: "c031",
    parentKey: "aos-s2",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 2 · Eps 20–22",
  },
  {
    id: "c032",
    parentKey: "daredevil-s2",
    title: "Daredevil",
    sub: "Season 2 · Eps 1–4",
  },
  {
    id: "c033",
    parentKey: "luke-cage-s1",
    title: "Luke Cage",
    sub: "Season 1 · Eps 1–4",
  },
  {
    id: "c034",
    parentKey: "daredevil-s2",
    title: "Daredevil",
    sub: "Season 2 · Eps 5–11",
  },
  {
    id: "c035",
    parentKey: "luke-cage-s1",
    title: "Luke Cage",
    sub: "Season 1 · Eps 5–8",
  },
  {
    id: "c036",
    parentKey: "daredevil-s2",
    title: "Daredevil",
    sub: "Season 2 · Eps 12–13",
  },
  {
    id: "c037",
    parentKey: "luke-cage-s1",
    title: "Luke Cage",
    sub: "Season 1 · Eps 9–13",
  },
  { id: "c038", parentKey: "ant-man", title: "Ant-Man" },
  {
    id: "c039",
    parentKey: "aos-s3",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 3 · Eps 1–10",
  },
  {
    id: "c040",
    parentKey: "aos-s3",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 3 · Eps 11–19",
  },
  {
    id: "c041",
    parentKey: "iron-fist-s1",
    title: "Iron Fist",
    sub: "Season 1",
  },
  {
    id: "c042",
    parentKey: "cap-civil-war",
    title: "Captain America: Civil War",
  },
  { id: "c043", parentKey: "team-thor-1", title: "Team Thor", sub: "One-Shot" },
  {
    id: "c044",
    parentKey: "team-thor-2",
    title: "Team Thor: Part 2",
    sub: "One-Shot",
  },
  {
    id: "c045",
    parentKey: "black-widow",
    title: "Black Widow",
    note: "Watch credits scene after Avengers: Endgame",
  },
  {
    id: "c046",
    parentKey: "aos-s3",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 3 · Eps 20–22",
  },
  {
    id: "c047",
    parentKey: "the-defenders",
    title: "The Defenders",
    sub: "Season 1",
  },
  {
    id: "c048",
    parentKey: "aos-s4",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 4 · Eps 1–6",
  },
  { id: "c049", parentKey: "doctor-strange", title: "Doctor Strange" },
  { id: "c050", parentKey: "black-panther", title: "Black Panther" },
  {
    id: "c051",
    parentKey: "aos-s4",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 4 · Eps 7–8",
  },
  {
    id: "c052",
    parentKey: "aos-slingshot",
    title: "Agents of S.H.I.E.L.D.: Slingshot",
    sub: "Season 1 · Eps 1–6",
  },
  {
    id: "c053",
    parentKey: "aos-s4",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 4 · Eps 9–22",
  },
  {
    id: "c054",
    parentKey: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
  },
  { id: "c055", parentKey: "thor-ragnarok", title: "Thor: Ragnarok" },
  {
    id: "c056",
    parentKey: "team-darryl",
    title: "Team Darryl",
    sub: "One-Shot",
  },
  { id: "c057", parentKey: "inhumans-s1", title: "Inhumans", sub: "Season 1" },
  {
    id: "c058",
    parentKey: "punisher-s1",
    title: "The Punisher",
    sub: "Season 1",
  },
  { id: "c059", parentKey: "runaways-s1", title: "Runaways", sub: "Season 1" },
  {
    id: "c060",
    parentKey: "aos-s5",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 5 · Eps 1–10",
  },
  {
    id: "c061",
    parentKey: "jessica-jones-s2",
    title: "Jessica Jones",
    sub: "Season 2",
  },
  {
    id: "c062",
    parentKey: "aos-s5",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 5 · Eps 11–18",
  },
  {
    id: "c063",
    parentKey: "cloak-dagger-s1",
    title: "Cloak & Dagger",
    sub: "Season 1",
  },
  {
    id: "c064",
    parentKey: "cloak-dagger-s2",
    title: "Cloak & Dagger",
    sub: "Season 2",
  },
  {
    id: "c065",
    parentKey: "luke-cage-s2",
    title: "Luke Cage",
    sub: "Season 2",
  },
  {
    id: "c066",
    parentKey: "iron-fist-s2",
    title: "Iron Fist",
    sub: "Season 2",
  },
  {
    id: "c067",
    parentKey: "daredevil-s3",
    title: "Daredevil",
    sub: "Season 3",
  },
  { id: "c068", parentKey: "runaways-s2", title: "Runaways", sub: "Season 2" },
  {
    id: "c069",
    parentKey: "punisher-s2",
    title: "The Punisher",
    sub: "Season 2",
  },
  {
    id: "c070",
    parentKey: "jessica-jones-s3",
    title: "Jessica Jones",
    sub: "Season 3",
  },
  {
    id: "c071",
    parentKey: "ant-man-wasp",
    title: "Ant-Man and the Wasp",
    note: "Watch credits scene after Infinity War",
  },
  { id: "c072", parentKey: "infinity-war", title: "Avengers: Infinity War" },
  {
    id: "c073",
    parentKey: "aos-s5",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 5 · Eps 19–22",
    note: "Concurrent with Infinity War",
  },
  {
    id: "c074",
    parentKey: "aos-s6",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 6",
    note: "During Endgame’s 5–year time jump",
  },
  {
    id: "c075",
    parentKey: "aos-s7",
    title: "Agents of S.H.I.E.L.D.",
    sub: "Season 7",
    note: "During Endgame’s 5–year time jump",
  },
  {
    id: "c076",
    parentKey: "runaways-s3",
    title: "Runaways",
    sub: "Season 3",
    note: "Mostly post-Snap",
  },
  { id: "c077", parentKey: "endgame", title: "Avengers: Endgame" },
  { id: "c078", parentKey: "loki-s1", title: "Loki", sub: "Season 1" },
  { id: "c079", parentKey: "loki-s2", title: "Loki", sub: "Season 2" },
  {
    id: "c080",
    parentKey: "what-if-s1",
    title: "What If…?",
    sub: "Season 1",
  },
  {
    id: "c081",
    parentKey: "what-if-s2",
    title: "What If…?",
    sub: "Season 2",
  },
  {
    id: "c082",
    parentKey: "what-if-s3",
    title: "What If…?",
    sub: "Season 3",
  },
  { id: "c083", parentKey: "marvel-zombies", title: "Marvel Zombies" },
  { id: "c084", parentKey: "wandavision", title: "WandaVision" },
  {
    id: "c085",
    parentKey: "deadpool-wolverine",
    title: "Deadpool & Wolverine",
  },
  {
    id: "c086",
    parentKey: "shang-chi",
    title: "Shang-Chi and the Legend of the Ten Rings",
  },
  {
    id: "c087",
    parentKey: "falcon-ws",
    title: "The Falcon and the Winter Soldier",
  },
  { id: "c088", parentKey: "eternals", title: "Eternals" },
  {
    id: "c089",
    parentKey: "spider-man-ffh",
    title: "Spider-Man: Far From Home",
  },
  { id: "c090", parentKey: "spider-man-nwh", title: "Spider-Man: No Way Home" },
  {
    id: "c091",
    parentKey: "doctor-strange-2",
    title: "Doctor Strange in the Multiverse of Madness",
  },
  { id: "c092", parentKey: "hawkeye", title: "Hawkeye" },
  { id: "c093", parentKey: "moon-knight", title: "Moon Knight" },
  {
    id: "c094",
    parentKey: "bp-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
  },
  { id: "c095", parentKey: "echo", title: "Echo" },
  { id: "c096", parentKey: "she-hulk", title: "She-Hulk: Attorney at Law" },
  { id: "c097", parentKey: "ms-marvel", title: "Ms. Marvel" },
  {
    id: "c098",
    parentKey: "thor-love-thunder",
    title: "Thor: Love and Thunder",
  },
  {
    id: "c099",
    parentKey: "ironheart-s1",
    title: "Ironheart",
    sub: "Season 1",
  },
  { id: "c100", parentKey: "werewolf-night", title: "Werewolf By Night" },
  {
    id: "c101",
    parentKey: "gg-holiday-special",
    title: "The Guardians of the Galaxy Holiday Special",
  },
  {
    id: "c102",
    parentKey: "ant-man-quantumania",
    title: "Ant-Man and The Wasp: Quantumania",
  },
  {
    id: "c103",
    parentKey: "guardians-3",
    title: "Guardians of the Galaxy Vol. 3",
  },
  { id: "c104", parentKey: "secret-invasion", title: "Secret Invasion" },
  { id: "c105", parentKey: "marvels", title: "The Marvels" },
  { id: "c106", parentKey: "agatha-all-along", title: "Agatha All Along" },
  {
    id: "c107",
    parentKey: "daredevil-ba-s1",
    title: "Daredevil: Born Again",
    sub: "Season 1",
  },
  {
    id: "c108",
    parentKey: "cap-brave-new-world",
    title: "Captain America: Brave New World",
  },
  { id: "c109", parentKey: "thunderbolts", title: "Thunderbolts*" },
  {
    id: "c110",
    parentKey: "fantastic-four",
    title: "The Fantastic Four: First Steps",
  },
  {
    id: "c111",
    parentKey: "wonder-man-s1",
    title: "Wonder Man",
    sub: "Season 1",
  },
  {
    id: "c112",
    parentKey: "daredevil-ba-s2",
    title: "Daredevil: Born Again",
    sub: "Season 2",
  },
];

const TYPE_CONFIG = {
  movie: { label: "Film", color: "#d4af37", bg: "rgba(212,175,55,0.12)" },
  series: { label: "Series", color: "#60a5fa", bg: "rgba(96,165,250,0.12)" },
  oneshot: {
    label: "One-Shot",
    color: "#c084fc",
    bg: "rgba(192,132,252,0.12)",
  },
  special: { label: "Special", color: "#f472b6", bg: "rgba(244,114,182,0.12)" },
};

const STATUS_CONFIG = {
  watched: { label: "Watched", icon: "✓", color: "#4ade80", bar: "#166534" },
  watching: { label: "Watching", icon: "▶", color: "#60a5fa", bar: "#1e3a5f" },
  "will-watch": {
    label: "Will Watch",
    icon: "◎",
    color: "#c084fc",
    bar: "#3b0764",
  },
  skip: { label: "Skip", icon: "✕", color: "#6b7280", bar: "#1c1c1c" },
};

const STORAGE_KEY = "mcu-tracker-v1";
